### ISSUE TITLE
Getting compilation Errors on Xcode 11.

### ISSUE THREAD

**Issue by krishnagniyes** [Giphy/giphy-ios-sdk-ui-example#45]
Getting compilation Errors on Xcode 11, but it's working fine on Xcode 11.2

###Please find attached screenshots:

<img width="642" alt="Screen Shot 2019-12-19 at 9 17 45 PM" src="https://user-images.githubusercontent.com/1003632/71232255-14f90100-22a6-11ea-9354-0d3bb57fde36.png">
<img width="565" alt="Screen Shot 2019-12-19 at 9 17 38 PM" src="https://user-images.githubusercontent.com/1003632/71232256-14f90100-22a6-11ea-9736-2c81d14535fb.png">

We want to use Giffy SDK in our project, but it's not compiling on Xcode 11. 

Please do the needful.

Thanks
Krishna

**Comment by krishnagniyes** [comment]
Seems v1.1.3 is working on xcode 11. But I've one more question, What is the size of this framework? I was not able to find it.

Please do the needful.

Thanks
Krishna

**Comment by cgmaier** [comment]
hi @krishnagniyes ! we've improved the GIPHY SDK quite a bit since v1.1.3 and so highly recommend you upgrade to the latest version of Xcode so you can use the latest version of GIPHY. 

we've also achieved module stability with the latest version of the GIPHY SDK (v1.1.8), and so it should be compatible with all future versions of Xcode. 

I'm not certain what the exact footprint is of the SDK is on .ipa size of an archived app, and I'm unsure if this may vary across versions of Xcode. My guess is that the footprint is negligible (<1mb).

**Comment by krishnagniyes** [comment]
@cgmaier, Thanks for the prompt response. Is there a way if we can customize GiffyViewController? Specially collection view from 2 columns to 3 columns?
