### ISSUE TITLE
Could not cast 'GiphyCoreSDK.GPHMedia' to 'GiphyCoreSDK.GPHMedia'

### ISSUE THREAD

**Issue by AlexClarkQP** [Giphy/giphy-ios-sdk-ui-example#17]
I’m getting an odd error with the following code after updating Giphy via Cocoapods:

let media = inst as! GPHMedia

The error is:

Could not cast value of type 'GiphyCoreSDK.GPHMedia' (0x10e425fc8) to 'GiphyCoreSDK.GPHMedia' (0x109e9f770).

This worked before I did ‘pod update” and no other changes were made. I’ve cleared the Xcode cache and re-initialized Cocopods but still no luck. I’ve also verified (via the debugger) that “Inst” is an instance of  GPHMedia. Any thoughts on why this would fail after an update?

**Comment by AlexClarkQP** [comment]
Some extra (hopefully useful) info... I rolled back the version to 1.0.1 (from 1.0.2) in my podfile and the code is working again:

Podfile:
pod 'Giphy','1.0.1'

Pod output:
"Installing Giphy 1.0.1 (was 1.0.2)"

**Comment by cgmaier** [comment]
hey @AlexClarkQP thanks for reaching out, that's very strange! I wasn't able to reproduce this. where does `inst` come from? what's your version of Cocoapods?

**Comment by AlexClarkQP** [comment]
Hello, thank you very much for your help. I'm glad I could find a strange one. ;-) 

The instance comes from GiphyViewController:

    func onGiphy() {
        let vc = GiphyViewController()
        vc.delegate = self
        present(vc, animated: true, completion: nil)
    }

Specifically, I get it in the delegate callback:

    func didSelectMedia(giphyViewController: GiphyViewController, media: GPHMedia) {
        _ = displayNode.add(giphyMedia: media)
        giphyViewController.dismiss(animated: true, completion: nil)
    }

I then take that instance and add it to an array of Any since I hold other media there too (UIImage and PHAsset). Later I loop through what was selected and determine the type like this:


    for media in selectedMedia {
        if let inst = media as? UIImage {
            // Do stuff 
        }
        else if let inst = media as? PHAsset {
            // Do stuff
        }
        else if let inst = media as? GPHMedia {
            // Do stuff
        }
    }

The first two (UIImage and PHAsset) work as expected. The third works fine as long as I stay on version 1.0.1. My Cocoapods version is 1.7.5.

**Comment by cgmaier** [comment]
ah interesting, so this is a crash at runtime, and not a compilation error?

**Comment by AlexClarkQP** [comment]
That's correct. It compiles fine but when it runs I get that error. If I pause and check it in the debugger it shows as an instance of GPHMedia. It's almost like an old class instance from 1.0.1 is hanging around and causes that issues when I upgrade to 1.0.2. However, the code is pretty simple and I've cleared cache on xcode, re-initialized cocoapods and no luck.

**Comment by cgmaier** [comment]
hey @AlexClarkQP thanks so much for the additional details. could you do me a huge favor and try running these commands?
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by AlexClarkQP** [comment]
Unfortunately that didn't work. However, I have done some experimenting and have some info which may be helpful.

If I use version 1.0.2, I get the exception as I noted at the start of this issue.

If I use version 1.0.1, the interface doesn't look quite right (missing the search icon - see attachment, "new_build_system.png") and I get the following warning (but the cast issue goes away):

: - 1: ignoring duplicated output file: '/Users/alexclark/Library/Developer/Xcode/DerivedData/Eagle-ainrmrpcxhhwydaspsbwhwgdlcmo/Build/Products/Debug-iphonesimulator/Eagle.app/Assets.car' in shell script build phase '[CP] Copy Pods Resources'. This warning represents an extremely serious project misconfiguration and will likely cause some shell scripts in your project to be skipped entirely, leading to other build failures or missing files in the build directory. This will be a hard error in the future. (in target 'Eagle')

If I switch to the legacy build system with 1.0.1, the warning goes away and the interface looks as it should. Also the cast error goes away. This seems to be the only build combination that works for me. Unfortunately, I can't upgrade to 1.0.2.

I've attached two files:

new_build_system.png: Shows the interface with 1.0.1 built with the new build system for xcode. Notice the interface isn't right (missing search icon and back button) and I get the project misconfiguration warning mentioned above.

<img width="200" alt="new_build_system" src="https://user-images.githubusercontent.com/54222682/63500284-474e4980-c4d2-11e9-8ceb-aa14c8acef48.png">

legacy_build_system.png: Shows the interface with 1.0.1 built with the legacy build system for xcode. All works fine except I have to be on the legacy build system and can't upgrade GIPHY.

<img width="200" alt="legacy_build_system" src="https://user-images.githubusercontent.com/54222682/63500292-49b0a380-c4d2-11e9-89f0-d6cce5a033b9.png">

Could this be a project configuration issue that comes up with version 1.0.2 of GIPHY? I found this which may also be helpful (but I couldn’t get any settings to work for me):

https://stackoverflow.com/questions/52398521/flutter-ios-build-failure-error-with-multiple-commands-after-the-xcode-upgrade

**Comment by AlexClarkQP** [comment]
Thanks Chris I really appreciate it. I'm happy to send you any project files you need to help diagnose (offline of course).

**Comment by AlexClarkQP** [comment]
Thank you for the update. I tried it out and clicking on a gif presented in the Giphy display node now freezes the simulator. I'm guessing it may be a problem with the pre release build of xcode but I'm going to try a few things to be sure. I'll keep you posted!

**Comment by cgmaier** [comment]
hey @AlexClarkQP let us know if you've resolved this : )

**Comment by AlexClarkQP** [comment]
I'm happy to report I got my environment working again with the latest XCode and it's working! Thank you again for all your help.

**Comment by cgmaier** [comment]
thanks for following up on this @AlexClarkQP !! gonna close
